language: android
jdk: oraclejdk10
android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-27.0.3
  - android-28
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-26
before_install:
  - openssl aes-256-cbc -K $encrypted_d9c70d14fbf6_key -iv $encrypted_d9c70d14fbf6_iv
  - in google-services.json.enc -out app/google-services.json -d
before_script:
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - curl http://is.gd/android_wait_for_emulator > android-wait-for-emulator
  - chmod u+x android-wait-for-emulator
  - ./android-wait-for-emulator
  - adb shell input keyevent 82 &
script: "./gradlew test"
