language: android
jdk: oraclejdk10
android:
  components:
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools
    -tools

    # The BuildTools version used by the project
    - build-tools-28.0.0

    # The SDK version used to compile the project
    - android-28

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-26

script: ./gradlew test

